### ISSUE TITLE
`NoSuchFileException` thrown at times with Metals and sbt

### ISSUE THREAD

**Issue by ckipp01** [swoval/swoval#140]
Hello! I've hesitated to open this without a good reproduction, but I've seen it a handful of times, so I figured I'd open an issue to maybe get some ideas from you about what could be going on, or how I could pinpoint it next time it happens.

I've noticed this a few times when tailing logs while working on Metals, and today I noticed it for the first time from sbt while working on the [sbt bsp integration](https://github.com/scalameta/metals/pull/2154). That's another reason I hesitate to open since this _always_ happens when I'm developing  the project, using snapshots, etc.

Today I was testing on the mdoc codebase, and I got this in the logs. The exception is pretty much the same every time I see it:

```
Caught unexpected io exception handling event for /Users/ckipp/Documents/scala-workspace/scalameta-org/mdoc/tests/jsdocs/src/test/java
java.nio.file.NoSuchFileException: /Users/ckipp/Documents/scala-workspace/scalameta-org/mdoc/tests/jsdocs/src/test/java
        at com.swoval.files.NativeDirectoryLister.fillResults(NativeDirectoryLister.java:93)
        at com.swoval.files.NativeDirectoryLister.apply(NativeDirectoryLister.java:48)
        at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:149)
        at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
        at com.swoval.files.SimpleFileTreeView.list(SimpleFileTreeView.java:50)
        at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:568)
        at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:557)
        at com.swoval.files.FileCacheDirectoryTree.newCachedDirectory(FileCacheDirectoryTree.java:623)
        at com.swoval.files.FileCacheDirectoryTree.handleEvent(FileCacheDirectoryTree.java:298)
        at com.swoval.files.FileTreeRepositories$1.onNext(FileTreeRepositories.java:79)
        at com.swoval.files.FileTreeRepositories$1.onNext(FileTreeRepositories.java:73)
        at com.swoval.files.Observers.onNext(Observers.java:31)
        at com.swoval.files.ApplePathWatcher$1.accept(ApplePathWatcher.java:285)
        at com.swoval.files.ApplePathWatcher$1.accept(ApplePathWatcher.java:259)
        at com.swoval.files.apple.FileEventMonitorImpl$WrappedConsumer$1.run(FileEventMonitors.java:178)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

And as you can see, the `/src/java` directory doesn't exist:

```
~/Documents/scala-workspace/scalameta-org/mdoc/tests/jsdocs master*
❯ tree -L 3
.
├── src
│  └── main
│     └── scala
└── target
   ├── scala-2.12
   │  ├── classes
   │  ├── entrypoints-fastopt.txt
   │  ├── entrypoints-fullopt.txt
   │  ├── meta
   │  ├── scalajs-bundler
   │  ├── update
   │  └── zinc
   └── streams
      ├── _global
      ├── compile
      ├── it
      ├── runtime
      └── test
```
Whenver I saw this exception, it's always been the same, it's looking for `/src/java` when it doesn't exist in the project I'm on. I've never noticed it having any real impact on the actual functionality of the file watching, and probably would never have noticed it if I wasn't tailing my logs.

Some system details that _may_ help.

OS: macOS Catalina v10.15.7
jdk: openjdk version "1.8.0_242"

Let me know if there is anything else I can provide or look at if I see this again.

Cheers and thanks for all your work!

**Comment by eatkins** [comment]
Thanks for reporting this! It is a strange situation. A simple fix would just be to catch a NoSuchFileException and ignore it but I'm curious as to what is going on here. The code that is causing the printing to System.err should only run if a file event is detected for `src/test/java` and the file exists at the time that the event is detected but no longer exists by the time that the event callback is run. This could theoretically be caused by some code that creates the directory and then immediately deletes it, but that seems unlikely. It would help if you ran with `-Dswoval.log.level=debug` (which is very verbose). This should identify specifically what events are detected by the file monitor so we could figure out the sequence of events that leads to this behavior.

**Comment by ckipp01** [comment]
> It would help if you ran with -Dswoval.log.level=debug (which is very verbose). This should identify specifically what events are detected by the file monitor so we could figure out the sequence of events that leads to this behavior.

Sounds good. I'll try to do this and report back any findings. Again, this doesn't happen often, so it may be a bit before I get any useful info.

**Comment by ckipp01** [comment]
So since reporting this and enabling verbose logging (which sure gave me a lot of logs 😆), I'm happy to say that I haven't seen this happen again. So I'm happy to report that, but sad I couldn't help figure out what was happening. Either way, I appreciate the help and response. I'll close this for now and if I ever see this start popping up again I can revisit and try to provide more.

**Comment by eatkins** [comment]
The dreaded Heisenbug. I'm both glad that it isn't happening and disappointed that we don't have a repro. Please report back if it crops up again.
