### ISSUE TITLE
java.io.IOException: Function not implemented (inotify in docker/rancher on macos)

### ISSUE THREAD

**Issue by pecasdev** [swoval/swoval#160]
When running github action locally with [act](https://github.com/nektos/act) and this step:
```yaml
- name: Compile and test
  run: sbt compile test
```
I get the following error

```java
java.io.IOException: Function not implemented
| 	at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
| 	at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
| 	at com.swoval.files.RegisterableWatchServices$RegisterableWatchServiceImpl.<init>(RegisterableWatchServices.java:34)
| 	at com.swoval.files.RegisterableWatchServices.get(RegisterableWatchServices.java:21)
| 	at com.swoval.files.PlatformWatcher.make(PlatformWatcher.java:11)
| 	at com.swoval.files.PathWatchers.get(PathWatchers.java:85)
| 	at com.swoval.files.FileTreeRepositories.get(FileTreeRepositories.java:64)
| 	at com.swoval.files.FileTreeRepositories.get(FileTreeRepositories.java:32)
| 	at sbt.internal.nio.FileTreeRepositoryImpl.<init>(FileTreeRepositoryImpl.scala:47)
| 	at sbt.internal.nio.FileTreeRepository$.default(FileTreeRepository.scala:40)
| 	at sbt.BuiltinCommands$.$anonfun$setupGlobalFileTreeRepository$1(Main.scala:984)
| 	at sbt.BuiltinCommands$.$anonfun$doLoadProject$5(Main.scala:976)
| 	at sbt.Project$.setProject(Project.scala:501)
| 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:976)
| 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:914)
| 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
| 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
| 	at sbt.Command$.process(Command.scala:189)
| 	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
| 	at scala.Option.getOrElse(Option.scala:189)
| 	at sbt.MainLoop$.process$1(MainLoop.scala:245)
| 	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
| 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
| 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
| 	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
| 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
| 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
| 	at sbt.MainLoop$.next(MainLoop.scala:163)
| 	at sbt.MainLoop$.run(MainLoop.scala:144)
| 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
| 	at sbt.io.Using.apply(Using.scala:27)
| 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
| 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
| 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
| 	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
| 	at sbt.StandardMain$.runManaged(Main.scala:223)
| 	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
| 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:389)
| 	at sbt.xMain$.withStreams$1(Main.scala:87)
| 	at sbt.xMain$.run(Main.scala:121)
| 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
| 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
| 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
| 	at sbt.xMain.run(Main.scala:46)
| 	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
| 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
| 	at xsbt.boot.Launch$.run(Launch.scala:149)
| 	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
| 	at xsbt.boot.Launch$.launch(Launch.scala:159)
| 	at xsbt.boot.Launch$.apply(Launch.scala:44)
| 	at xsbt.boot.Launch$.apply(Launch.scala:21)
| 	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
| 	at xsbt.boot.Boot$.run(Boot.scala:73)
| 	at xsbt.boot.Boot$.main(Boot.scala:21)
| 	at xsbt.boot.Boot.main(Boot.scala)
| [error] java.io.IOException: Function not implemented
| [error] Use 'last' for the full log.
| [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

I've seen this error reported in other places, namely [this stackoverflow link](https://stackoverflow.com/questions/72842770/sbt-1-6-2-java-io-ioexception-function-not-implemented).

The problem seems to be that inotify is not implemented for the docker host. Swoval should have caught the error in the above stack trace.

**Comment by eatkins** [comment]
There is nothing swoval can do about this.  Sbt assumes that if it looks like linux that inotify works.

The proper fix is for the macos docker to implement inotify, not for this library to make a workaround for busted playform.
