### ISSUE TITLE
NPE on load

### ISSUE THREAD

**Issue by cquiroz** [swoval/swoval#87]
I've hit this NPE when using `CloseWatchPlugin` Any ideas?

```
[error] java.lang.NullPointerException
[error] 	at com.swoval.watchservice.CloseWatchPlugin$PathWatcherOps.register(CloseWatchPlugin.scala:23)
[error] 	at com.swoval.watchservice.CloseWatchPlugin$.$anonfun$cachedSourcesFor$2(CloseWatchPlugin.scala:67)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at com.swoval.watchservice.CloseWatchPlugin$.$anonfun$cachedSourcesFor$1(CloseWatchPlugin.scala:84)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / sources) java.lang.NullPointerException
```

**Comment by eatkins** [comment]
Yes. I'll have a fix soon. Thanks for the report.

**Comment by eatkins** [comment]
I published a new version, 2.0.4, that should hopefully fix this. Please report back.

**Comment by cquiroz** [comment]
The NPE is gone but I'm seeing this now:
```
[warn] Run 'evicted' to see detailed eviction warnings
[error] java.lang.IllegalStateException: Global file repository was not previously registered
[error] 	at com.swoval.watchservice.CloseWatchPlugin$.$anonfun$globalSettings$2(CloseWatchPlugin.scala:250)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at com.swoval.watchservice.CloseWatchPlugin$.$anonfun$globalSettings$1(CloseWatchPlugin.scala:250)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
```

**Comment by eatkins** [comment]
Do you override the `onLoad` task in your build? That is where the global file repository is initialized. If so, you might be able to fix the issue by adding
```
onLoad := { state =>
  onLoad.value(state)
  ...(your custom onLoad code)
}
```
You would also want to make the same change to `onUnload` if that is overridden as well.

**Comment by cquiroz** [comment]
Awesome, that works. thanks

**Comment by eatkins** [comment]
Great, thanks for the report!
